"""empty message

Revision ID: 12e08bdae651
Revises: 9d0a34e277d6
Create Date: 2020-08-04 22:27:21.968872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e08bdae651'
down_revision = '9d0a34e277d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('progress', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'progress')
    # ### end Alembic commands ###
