"""empty message

Revision ID: 4d5f670fe27e
Revises: 
Create Date: 2020-08-04 15:18:15.882534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d5f670fe27e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_timestamp'), 'user', ['timestamp'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_timestamp'), 'project', ['timestamp'], unique=False)
    op.create_table('draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('section_1_title', sa.String(), nullable=True),
    sa.Column('section_2_title', sa.String(), nullable=True),
    sa.Column('section_3_title', sa.String(), nullable=True),
    sa.Column('section_4_title', sa.String(), nullable=True),
    sa.Column('section_5_title', sa.String(), nullable=True),
    sa.Column('section_6_title', sa.String(), nullable=True),
    sa.Column('section_7_title', sa.String(), nullable=True),
    sa.Column('section_8_title', sa.String(), nullable=True),
    sa.Column('section_9_title', sa.String(), nullable=True),
    sa.Column('section_10_title', sa.String(), nullable=True),
    sa.Column('section_1_body', sa.Text(), nullable=True),
    sa.Column('section_2_body', sa.Text(), nullable=True),
    sa.Column('section_3_body', sa.Text(), nullable=True),
    sa.Column('section_4_body', sa.Text(), nullable=True),
    sa.Column('section_5_body', sa.Text(), nullable=True),
    sa.Column('section_6_body', sa.Text(), nullable=True),
    sa.Column('section_7_body', sa.Text(), nullable=True),
    sa.Column('section_8_body', sa.Text(), nullable=True),
    sa.Column('section_9_body', sa.Text(), nullable=True),
    sa.Column('section_10_body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_timestamp'), 'draft', ['timestamp'], unique=False)
    op.create_table('idea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('idea_freewrite', sa.String(), nullable=True),
    sa.Column('idea_question', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idea_timestamp'), 'idea', ['timestamp'], unique=False)
    op.create_table('outline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('section_1_title', sa.String(), nullable=True),
    sa.Column('section_2_title', sa.String(), nullable=True),
    sa.Column('section_3_title', sa.String(), nullable=True),
    sa.Column('section_4_title', sa.String(), nullable=True),
    sa.Column('section_5_title', sa.String(), nullable=True),
    sa.Column('section_6_title', sa.String(), nullable=True),
    sa.Column('section_7_title', sa.String(), nullable=True),
    sa.Column('section_8_title', sa.String(), nullable=True),
    sa.Column('section_9_title', sa.String(), nullable=True),
    sa.Column('section_10_title', sa.String(), nullable=True),
    sa.Column('section_1_body', sa.Text(), nullable=True),
    sa.Column('section_2_body', sa.Text(), nullable=True),
    sa.Column('section_3_body', sa.Text(), nullable=True),
    sa.Column('section_4_body', sa.Text(), nullable=True),
    sa.Column('section_5_body', sa.Text(), nullable=True),
    sa.Column('section_6_body', sa.Text(), nullable=True),
    sa.Column('section_7_body', sa.Text(), nullable=True),
    sa.Column('section_8_body', sa.Text(), nullable=True),
    sa.Column('section_9_body', sa.Text(), nullable=True),
    sa.Column('section_10_body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outline_timestamp'), 'outline', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outline_timestamp'), table_name='outline')
    op.drop_table('outline')
    op.drop_index(op.f('ix_idea_timestamp'), table_name='idea')
    op.drop_table('idea')
    op.drop_index(op.f('ix_draft_timestamp'), table_name='draft')
    op.drop_table('draft')
    op.drop_index(op.f('ix_project_timestamp'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_user_timestamp'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
